Repository victoriaaraujo10/diario-viagens, pull requests merged in 2022-06, with the labels that each got.

#22 Criação de botão que muda a toobar
  src/app/core/components/navbar/navbar.component.html
  src/app/core/components/navbar/navbar.component.scss
  src/app/core/components/navbar/navbar.component.ts
Labels: enhancement

#30 Adição de Tooltips
  src/app/auth/components/cadastro/cadastro.component.html
  src/app/auth/components/login/login.component.html
  src/app/auth/components/recuperar-senha/recuperar-senha.component.html
  src/app/core/components/navbar/navbar.component.html
Labels: documentation, enhancement

#38 Dashboard: Total de usuários registrados na rede
  angular.json
  firebase.json
  package-lock.json
  package.json
  src/app/auth/components/cadastro/cadastro.component.ts
  src/app/auth/components/login/login.component.ts
  src/app/core/services/dashboard/dashboard.service.ts
  src/app/dashboard/dashboard-routing.module.ts
  src/app/dashboard/dashboard.component.html
  src/app/dashboard/dashboard.component.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: documentation
